Repository TeamDATEROAD/DATEROAD-ANDROID, pull requests merged in 2024-07, with the labels that each got.

#4 [init] 폰트 초기세팅
  app/src/main/java/org/sopt/dateroad/ui/theme/Type.kt
  app/src/main/res/font/suit_bold.ttf
  app/src/main/res/font/suit_extrabold.ttf
  app/src/main/res/font/suit_extralight.ttf
  app/src/main/res/font/suit_medium.ttf
  app/src/main/res/font/suit_regular.ttf
  app/src/main/res/font/suit_semibold.ttf
Labels: 🐻‍❄️ 민석 🐻‍❄️, ⚡️ init ⚡️

#8 [init] 아이콘 초기세팅
  app/src/main/res/drawable/btn_course_detail_more_black.xml
  app/src/main/res/drawable/btn_course_detail_more_white.xml
  app/src/main/res/drawable/btn_enroll_delete_picture.xml
  app/src/main/res/drawable/btn_look_button_arrow.xml
  app/src/main/res/drawable/btn_my_profile_plus.xml
  app/src/main/res/drawable/ic_all_camera.xml
  app/src/main/res/drawable/ic_all_clock_12.xml
  app/src/main/res/drawable/ic_all_clock_14.xml
  app/src/main/res/drawable/ic_all_close.xml
  app/src/main/res/drawable/ic_all_location_14.xml
  app/src/main/res/drawable/ic_all_money_12.xml
  app/src/main/res/drawable/ic_all_money_14.xml
  app/src/main/res/drawable/ic_all_plus_gray_300.xml
  app/src/main/res/drawable/ic_all_plus_white.xml
  app/src/main/res/drawable/ic_area_dropdown.xml
  app/src/main/res/drawable/ic_bottom_sheet_close.xml
  app/src/main/res/drawable/ic_coures_detail_heart_default.xml
  app/src/main/res/drawable/ic_course_detail_clock.xml
  app/src/main/res/drawable/ic_course_detail_heart_selected.xml
  app/src/main/res/drawable/ic_date_schedule_delete_course.xml
  app/src/main/res/drawable/ic_date_schedule_move_course.xml
  app/src/main/res/drawable/ic_enorll_camera.xml
  app/src/main/res/drawable/ic_enroll_calendar.xml
  app/src/main/res/drawable/ic_enroll_dropdown.xml
  app/src/main/res/drawable/ic_enroll_time.xml
  app/src/main/res/drawable/ic_home_plus_purple.xml
  app/src/main/res/drawable/ic_home_right_arrow_purple.xml
  app/src/main/res/drawable/ic_my_page_arrow.xml
  app/src/main/res/drawable/ic_my_page_pencil.xml
  app/src/main/res/drawable/ic_my_page_point_record_arrow.xml
  app/src/main/res/drawable/ic_nav_home_default.xml
  app/src/main/res/drawable/ic_nav_home_selected.xml
  app/src/main/res/drawable/ic_nav_look_default.xml
  app/src/main/res/drawable/ic_nav_look_selected.xml
  app/src/main/res/drawable/ic_nav_my_page_default.xml
  app/src/main/res/drawable/ic_nav_my_page_selected.xml
  app/src/main/res/drawable/ic_nav_read_default.xml
  app/src/main/res/drawable/ic_nav_read_selected.xml
  app/src/main/res/drawable/ic_nav_search_default.xml
  app/src/main/res/drawable/ic_nav_search_selected.xml
  app/src/main/res/drawable/ic_nav_timeline_default.xml
  app/src/main/res/drawable/ic_nav_timeline_selected.xml
  app/src/main/res/drawable/ic_tag_heart.xml
  app/src/main/res/drawable/ic_top_bar_back_black.xml
  app/src/main/res/drawable/ic_top_bar_back_white.xml
  app/src/main/res/drawable/ic_top_bar_share.xml
  app/src/main/res/drawable/img_profile_default.xml
  app/src/main/res/drawable/img_top_bar_profile.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ⚡️ init ⚡️

#6 [init] 컬러 초기세팅
  app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Theme.kt
Labels: 🎸 현진 🎸, ⚡️ init ⚡️

#11 [feat] Type 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/AdvertisementTitleType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/CourseDetailType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/DateTagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/EmptyViewType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/EnrollType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/GyeonggiAreaType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/IncheonAreaType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MoneyTagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MyCourseType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/OnboardingType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/OneButtonDialogType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/OneButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/PointBoxType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/PointHistoryTabType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/PointSystemType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/RegionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/SeoulAreaType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TimelineDetailType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TwoButtonDialogType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TwoButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#18 [init] Theme 기초 세팅
  app/src/main/java/org/sopt/dateroad/presentation/type/PointBoxType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Theme.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Type.kt
Labels: 🐸 지현 🐸, ⚡️ init ⚡️

#16 [feat] TabBar 컴포넌트
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tabbar/DateRoadTabBar.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#21 [feat] Chip 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/ChipType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadTextChip.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#24 [feat] Tag 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/TagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadImageTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadPointTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadTextTag.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#23 [feat] PointBox 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/PointBoxType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/pointbox/DateRoadMyPagePointBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/pointbox/DateRoadPointHistoryPointBox.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#25 [feat] Button 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadBasicButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadFilledButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadImageButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadKakaoLoginButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadOutlinedButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadTextButton.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt
  app/src/main/res/drawable/ic_kakao_logo.xml
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#26 [feat] Text Field 컴포넌트
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadBasicTextField.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextArea.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextFieldWithButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/model/TextFieldValidateResult.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#35 [feat] Course Card 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Course.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#37 [feat] Dialog 컴포넌트
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadOneButtonDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadOneButtonDialogWithDescription.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialogWithDescription.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#33 [feat] TopBar 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadCourseTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadHomeTopBar.kt
  app/src/main/res/drawable/ic_dateroad_logo.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#28 [feat] BottomSheet 컴포넌트
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBasicBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadPickerBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/numberpicker/DateRoadNumberPicker.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/numberpicker/PickerState.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#30 [feat] Place Card 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Place.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/PlaceCardType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#41 [refactor] Tag 컴포넌트 수정
  app/src/main/java/org/sopt/dateroad/presentation/type/DateTagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadImageTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadTextTag.kt
  app/src/main/res/drawable/ic_all_activity.xml
  app/src/main/res/drawable/ic_all_alcohol.xml
  app/src/main/res/drawable/ic_all_craft_shop.xml
  app/src/main/res/drawable/ic_all_drive.xml
  app/src/main/res/drawable/ic_all_epicurism.xml
  app/src/main/res/drawable/ic_all_exhibition_pop_up.xml
  app/src/main/res/drawable/ic_all_healing.xml
  app/src/main/res/drawable/ic_all_indoor.xml
  app/src/main/res/drawable/ic_all_nature.xml
  app/src/main/res/drawable/ic_all_performance_music.xml
  app/src/main/res/drawable/ic_all_shopping.xml
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, 💡 refactor 💡

#46 [refactor] Chip 아이콘 String -> Image
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadImageChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadTextChip.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#43 [feat] 마이페이지 개별 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/MyPageMenuType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MyPagePointInfoType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/mypage/DateRoadMyPageButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/mypage/DateRoadMyPagePointInfo.kt
  app/src/main/res/drawable/img_my_page_point_info.xml
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#42 [feat] ChipGroup 컴포넌트
  app/src/main/java/org/sopt/dateroad/presentation/type/ChipType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/DateChipGroupType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadImageChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadTextChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chipgroup/DateRoadDateChipGroup.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadImageTag.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#15 [feat] 하단 네비 바 구현
  app/src/main/java/org/sopt/dateroad/presentation/model/RouteModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MainNavigationBarItemType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/navigation/LookNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainBottomBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#47 [feat] DateSchedule 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/MainDate.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
  app/src/main/res/drawable/ic_home_plus_purple.xml
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#51 [feat] Advertisement 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Advertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#53 [feat] 코스 둘러보기 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Course.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/look/LookCourseCard.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#56 [feat] 포인트 내역 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/PointHistory.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/pointhistory/PointHistoryCard.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#63 [feat] 코스 등록하기 (Enroll) 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Place.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadPickerBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/model/Picker.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadBasicTextField.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextFieldWithButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollAddPhotoButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotoPreviewCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotos.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
  app/src/main/res/drawable/ic_enorll_camera.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#66 [feat] 포인트 내역 (PointHistory) 뷰 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Point.kt
  app/src/main/java/org/sopt/dateroad/domain/model/PointHistory.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/EmptyViewType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/PointHistoryTabType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/emptyview/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/DummyContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/navigation/DummyNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryPointBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/navigation/PointHistoryNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/base/BaseViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/base/UiState.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/view/LoadState.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/view/UiState.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#62 [feat] TimelineDateCard 컴포넌트 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Date.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/DateType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadImageTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/PastCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt
  app/src/main/res/drawable/bg_past_card.xml
  app/src/main/res/drawable/bg_timeline_card.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#68 [feat] 코스 둘러보기 (Look) 뷰 구현
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadAreaButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/emptyview/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadLeftTitleTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/component/LookCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/navigation/LookNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/res/drawable/ic_all_reset.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#72 [feat] MyCourse 뷰 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/EmptyViewType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/res/drawable/ic_empty_default.xml
  app/src/main/res/drawable/ic_empty_look.xml
  app/src/main/res/drawable/ic_empty_my_page_enroll.xml
  app/src/main/res/drawable/ic_empty_point_history.xml
  app/src/main/res/drawable/ic_empty_read.xml
  app/src/main/res/drawable/ic_empty_timeline.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#70 [feat] 안드로이드 12 스플래시 버전 대응
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#75 [feat] TimelineView 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/dateroad/presentation/type/OneButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/navigation/PastDateNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/base/BaseViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🎸 현진 🎸, ✨ feat ✨

#77 [fix] 코스 둘러보기 (Look) 뷰 지역 버튼 디자인 변경
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadAreaButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
Labels: 🐸 지현 🐸, 🫨 fix 🫨

#73 [feat] Profile View 구현
  app/src/main/java/org/sopt/dateroad/domain/model/EditProfile.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextFieldWithButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
  app/src/main/res/drawable/ic_enroll_profile_default.xml
  app/src/main/res/drawable/img_profile_default.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#69 [feat] Onboarding View 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/OnboardingType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/partialcolortext/PartialColorText.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/component/OnboardingIndicator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/res/drawable/img_onboarding_background1.png
  app/src/main/res/drawable/img_onboarding_background2.png
  app/src/main/res/drawable/img_onboarding_background3.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#85 [feat] Point Guide View 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/MyPagePointInfoType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/res/drawable/img_my_page_point_info_first.xml
  app/src/main/res/drawable/img_my_page_point_info_fourth.xml
  app/src/main/res/drawable/img_my_page_point_info_second.xml
  app/src/main/res/drawable/img_my_page_point_info_third.xml
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#79 [feat] 코스 등록 + 일정 등록 (Enroll) 뷰 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/DateChipGroupType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/EnrollScreenType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadFilledButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadBasicTextField.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollFirstScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollThirdScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotoPreviewCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotos.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#86 [feat] 마이페이지 (MyPage) 뷰 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Profile.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MyPageMenuType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/component/MyPageButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/component/MyPagePointBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/base/BaseViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/context/ContextExt.kt
  app/src/main/res/drawable/img_profile_default.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#93 [feat] 지난 데이트 (Past) 뷰 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/DateType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/component/PastCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/navigation/PastNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/PastDateViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pastdate/navigation/PastDateNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/navigation/PointHistoryNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#91 [feat] 열람한 코스 (Read) 뷰 구현
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/emptyview/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#89 [feat] HomeView 구현
  app/src/main/java/org/sopt/dateroad/domain/model/Advertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadPointTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadHomeTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/res/drawable/ic_dateroad_logo.xml
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#80 [feat] TimelineDetailView 구현
  app/src/main/java/org/sopt/dateroad/domain/model/DateDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadFilledButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialogWithDescription.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, ✨ feat ✨

#88 [feat] SignIn View 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadKakaoLoginButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dotsindicator/OnboardingIndicator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/webview/DateRoadWebView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/navigation/SignInNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#95 [feat] 코스 등록 Drag and Drop
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/draganddrop/DragAndDropListState.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/lazylist/LazyListExt.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/mutablelist/MutableListExt.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#99 [chore] Color Style Guide 변경
  app/src/main/java/org/sopt/dateroad/presentation/type/ChipType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/DateType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBasicBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadAreaButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadBasicButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadFilledButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadImageButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadKakaoLoginButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadOutlinedButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadTextButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dotsindicator/OnboardingIndicator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadPointTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadBasicTextField.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextArea.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextFieldWithButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryPointBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt
Labels: 🎸 현진 🎸, 💗 chore 💗

#94 [feat] Course Detail View 구현
  app/src/main/java/org/sopt/dateroad/domain/model/CourseDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailGradientBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailInfoBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/navigation/CourseDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/res/drawable/ic_course_detail_is_not_access.xml
  app/src/main/res/drawable/img_course_detail_dummy.png
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#104 [feat] Course Detail View Scroll 막기
  app/build.gradle.kts
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#97 [feat] 뷰 연결 및 스택 관리
  app/src/main/java/org/sopt/dateroad/domain/model/AdvertisementDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/model/CourseDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dotsindicator/DotsIndicator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/navigation/CourseDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/navigation/LookNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnBoardingContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnBoardingViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/navigation/PastNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/navigation/PointHistoryNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/navigation/SignInNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ✨ feat ✨

#108 [feat] 열람한 코스 (Read), 내가 등록한 코스 + 내가 열람한 코스 (MyCourse) 뷰 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/MyCourseRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/MyCourseRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseCourseDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseCoursesDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/MyCourseService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/ApiConstraints.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/DurationMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/LikeMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCoursesDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/MyCourseRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Course.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/MyCourseRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/type/MoneyTagType.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostMyCourseEnrollUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostMyCourseReadUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/MoneyTagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadTextChip.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadImageTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/component/LookCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadViewModel.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#110 [chore] Advertisement component 수정
  app/src/main/java/org/sopt/dateroad/domain/model/Advertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/AdvertisementTitleType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, 💗 chore 💗

#113 [feat] AdvertisementService API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AdvertisementRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AdvertisementRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseAdvertisementDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseAdvertisementsDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AdvertisementService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseAdvertisementDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseAdvertisementsDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AdvertisementRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Advertisement.kt
  app/src/main/java/org/sopt/dateroad/domain/model/AdvertisementDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AdvertisementRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetAdvertisementsUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#119 [feat] 닉네임 중복 체크 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetNicknameCheckUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#122 [feat] 마이페이지 사용자 프로필 조회 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/ProfileRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/ProfileRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseProfileDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/ProfileService.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseProfileDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/ProfileRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Profile.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/ProfileRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetUserUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/component/MyPagePointBox.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#124 [feat] 데이트 코스 삭제 API 연동
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#130 [feat] 유저 탈퇴 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestWithdrawDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/type/MoneyTagType.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/DeleteWithdrawUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadBasicButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialogWithDescription.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#131 [feat] 관리자 아카이빙(CourseDetail) API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AdvertisementRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AdvertisementRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseAdvertisementDetailDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AdvertisementService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/DateMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseAdvertisementDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AdvertisementRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/AdvertisementDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AdvertisementRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/type/AdvertisementTagType.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/DeleteCourseLikeUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetAdvertisementDetailUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#117 [feat] DateService API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/DateRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/DateRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseDateDetailDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseDateDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseDatesDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseNearestDateDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/DateService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/DateMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/PlaceMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseDateDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseDatesDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseNearestDateDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseTagDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/DateRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
  app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Date.kt
  app/src/main/java/org/sopt/dateroad/domain/model/DateDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/model/MainDate.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/DateRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/type/DateTimeType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/GyeonggiAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/IncheonAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/MonthType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/SeoulAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/DeleteDateUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetDateDetailUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetDatesUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetNearestDateUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/TimelineDetailType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#134 [feat] 코스 등록 + 일정 등록 (Enroll) 뷰 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/CourseRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/DateRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/CourseRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/DateRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestCourseDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestDateDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestPlaceDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestTagDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponsePointDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/CourseService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/DateService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/PlaceMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/TagMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/DateRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Enroll.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Point.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/CourseRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/DateRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/type/GyeonggiAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/IncheonAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/SeoulAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostCourseUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostDateUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/util/AreaMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollFirstScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollThirdScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailViewModel.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#135 [feat] Auth API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/dateroad/DateRoadApp.kt
  app/src/main/java/org/sopt/dateroad/data/datalocal/datasource/UserInfoLocalDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/datalocal/datasourceimpl/UserInfoLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestSignInDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestSignUpDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestTagsDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestUsePointDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestUserSignUpInfoDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseAuthDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseProfileDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/KakaoAuthService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/ContentUriRequestBody.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/SignInMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/TagsMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/UsePointMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/UserSignUpInfoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseAuthDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/NetworkModule.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/model/Auth.kt
  app/src/main/java/org/sopt/dateroad/domain/model/SignIn.kt
  app/src/main/java/org/sopt/dateroad/domain/model/SignUp.kt
  app/src/main/java/org/sopt/dateroad/domain/model/UsePoint.kt
  app/src/main/java/org/sopt/dateroad/domain/model/UserSignUpInfo.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/UserInfoRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/DeleteSignOutUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetAccessTokenUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetRefreshTokenUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostSignInUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostSignUpUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostUsePointUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/SetAccessTokenUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/SetRefreshTokenUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#127 [feat] 유저 프로필 조회(메인) API 연동
  app/src/main/java/org/sopt/dateroad/data/datalocal/datasource/UserInfoLocalDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/datalocal/datasourceimpl/UserInfoLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/UserPointRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/UserPointRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseUserPointDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/UserPointService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseUserPointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/UserPointRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/UserInfoRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/UserPointRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetRemainingPointsUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetUserIdUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/GetUserPointUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/SetRemainingPointsUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/SetUserIdUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadViewModel.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#133 [feat] 데이트 코스 필터링 조회(메인) API 연동
  app/src/main/java/org/sopt/dateroad/DateRoadApp.kt
  app/src/main/java/org/sopt/dateroad/domain/type/SortByType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
Labels: 🎸 현진 🎸, ✨ feat ✨

#138 [refactor] 코스 상세 UI & 열람 로직 수정
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestUsePointDto.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#141 [refactor] My Page View 포인트 제도 화면 연결 & 노션 웹뷰 연결
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/webview/DateRoadWebView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#142 [feat] 일정 - 코스 등록 플로우 정리
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/AreaMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CostMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CourseDetailMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/DateDetailMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/DateMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/DurationMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/LikeMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/PointMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/RegionMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/PlaceMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/PlaceMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseAdvertisementDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseDateDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseDatesDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseNearestDateDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePlaceDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseProfileDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseUserPointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/domain/model/CourseDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/model/DateDetail.kt
  app/src/main/java/org/sopt/dateroad/domain/type/GyeonggiAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/IncheonAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/type/SeoulAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/util/AreaMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/emptyview/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#144 [feat] 카카오톡 공유하기 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailViewModel.kt
  gradle/libs.versions.toml
Labels: 🎸 현진 🎸, ✨ feat ✨

#151 [feat] HomeScreen 리팩토링
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadHomeTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
Labels: 🎸 현진 🎸, 💡 refactor 💡

#157 [refactor] Home View SideEffect 적용
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#155 [refactor] UI 수정사항 반영Refactor UI
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/navigation/CourseDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
Labels: 🐸 지현 🐸, 💡 refactor 💡

#154 [refactor] Button 활성화 리팩토링
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBasicBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
Labels: 🎸 현진 🎸, 💡 refactor 💡

#158 [refactor] 네비게이션 애니메이션 제거
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/model/Picker.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/numberpicker/DateRoadNumberPicker.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/numberpicker/state/PickerState.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DataRoadIdeView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadErrorView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadWebView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/component/DateRoadMyPagePointInfo.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/navigation/PointGuideNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 💡 refactor 💡

#160 [refactor] 안드 자체 QA 사항 반영
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/domain/type/MoneyTagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadErrorView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, ✨ feat ✨

#163 [refactor] 전체 QA 사항 반영
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/DurationMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/partialcolortext/PartialColorText.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextArea.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailInfoBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeHotCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTimeLineCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#164 [refactor] 1차 QA 수정사항 반영
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CourseDetailMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadPickerBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/model/Picker.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadFilledButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadBasicTextField.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 💡 refactor 💡

#165 [feat] ReadMe
  README.md
Labels: 🎸 현진 🎸, 📚 docs 📚

#166 [refactor] 전체 QA 사항 반영
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTimeLineCard.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#171 [refactor] 백스택 관리
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#172 [feat] 프로필 수정 View 구현
  app/src/main/java/org/sopt/dateroad/presentation/type/OneButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/ProfileType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadDialog.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨
