Repository TeamDATEROAD/DATEROAD-ANDROID, pull requests merged in 2024-08, with the labels that each got.

#169 [refactor] 금액 String Mapper 수정
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/domain/model/CourseDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailInfoBar.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#191 [refactor] Home 화면 디자인 변경 적용
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
Labels: 🎸 현진 🎸, 💡 refactor 💡

#185 [fix] token reissue 중복 호출 해결
  app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
Labels: 🎸 현진 🎸, 🫨 fix 🫨

#198 [chore] 코스/일정 등록 뷰 지역 필터 바텀 시트 수정 (지역 전체 필터 제거)
  app/src/main/java/org/sopt/dateroad/presentation/type/DateRoadRegionBottomSheetType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
Labels: 🐸 지현 🐸, 💗 chore 💗

#196 [chore] 지역 관련 API 통신 Enum -> 한글 변경
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/AreaMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/domain/type/SeoulAreaType.kt
  app/src/main/java/org/sopt/dateroad/domain/util/Constraints.kt
Labels: 🐸 지현 🐸, 💗 chore 💗

#194 [refactor] 데이트 코스 상세 시작 시간 형식 변경
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseTimelineDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🎸 현진 🎸, 💡 refactor 💡

#199 [refactor] CourseDetail (코스 상세 + 관리자 아카이빙) 분기처리 리팩토링
  app/src/main/java/org/sopt/dateroad/presentation/type/CourseDetailType.kt
  app/src/main/java/org/sopt/dateroad/presentation/type/CourseDetailUnopenedDetailType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/advertisement/AdvertisementContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/advertisement/AdvertisementScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/advertisement/AdvertisementViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/advertisement/component/AdvertisementDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/advertisement/navigation/AdvertisementNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/pager/DateRoadImagePager.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadBasicTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/topbar/DateRoadScrollResponsiveTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailBasicInfo.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailBottomBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailCost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailGradientBox.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailOpenedDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailTimeline.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailUnopenedDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/navigation/CourseDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/navigation/LookNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointguide/PointGuideScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, 💡 refactor 💡

#187 [refactor] 에러 뷰, 로딩 뷰 추가 된 디자인 적용
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadErrorView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt
  app/src/main/res/drawable/ic_error_server.xml
  app/src/main/res/drawable/ic_loading_server.xml
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#202 [refactor] 코스 상세 뷰 시작시간 정보 추가
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailOpenedDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailTimeline.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💡 refactor 💡

#189 [feat] 코스 신고하기 웹 뷰 연결
  app/src/main/java/org/sopt/dateroad/presentation/type/TwoButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#174 [feat] 프로필 수정 API 연동
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestEditProfileDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/ProfileMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/domain/model/EditProfile.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PatchEditProfileUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#208 [chore] 자체 QA - 포인트 내역 (PointHistory) 뷰
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/PointMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointHistoryDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointsDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryCard.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 💗 chore 💗

#207 [chore] 자체 QA - 코스 상세(Course Detail) 뷰
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CostMapper.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailBasicInfo.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailInfoBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/drawable/ic_course_detail_is_not_access.png
  app/src/main/res/drawable/ic_course_detail_is_not_access.xml
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#210 [chore] 온보딩 뷰 디자인 수정
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#212 [chore] 자체 QA - 코스 등록 + 일정 등록 (Enroll) 뷰
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
Labels: 🐸 지현 🐸, 💗 chore 💗

#214 [chore] 자체 QA - 코스 둘러보기 (Look) 뷰
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
Labels: 🐸 지현 🐸, 💗 chore 💗

#216 [chore] 자체 디자인 QA - 이미지 파일 형식 수정
  app/src/main/res/drawable/ic_empty_look.png
  app/src/main/res/drawable/ic_empty_look.xml
  app/src/main/res/drawable/ic_empty_read.png
  app/src/main/res/drawable/ic_empty_read.xml
  app/src/main/res/drawable/ic_empty_timeline.png
  app/src/main/res/drawable/ic_empty_timeline.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#218 [chore] 자체 QA - 홈(Home) 뷰
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadPointTag.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeAdvertisement.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTopBar.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#221 [hotfix] 코스 불러오기를 통한 코스 등록이 안 되는 문제 해결
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/PlaceMapper.kt
Labels: 🐸 지현 🐸, 🔥 hotfix 🔥

#225 [fix] HOT 데이트 코스 LazyLow 수정
  app/src/main/java/org/sopt/dateroad/presentation/type/TagType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
Labels: 🎸 현진 🎸, 🫨 fix 🫨
