Repository TeamDATEROAD/DATEROAD-ANDROID, pull requests merged in 2024-09, with the labels that each got.

#227 [fix] 버튼 중복 클릭 문제 해결
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/modifier/ModifierExt.kt
Labels: 🐸 지현 🐸, 🫨 fix 🫨

#229 [chore] 포인트 내역 (PointHistory) 뷰 엠티뷰 이미지 변경
  app/src/main/java/org/sopt/dateroad/presentation/type/EmptyViewType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/res/drawable/ic_empty_point_history_minus.xml
  app/src/main/res/drawable/ic_empty_point_history_plus.xml
  app/src/main/res/drawable/img_empty_point_history_gained_history.xml
  app/src/main/res/drawable/img_empty_point_history_used_history.xml
Labels: 🐸 지현 🐸, 💗 chore 💗

#231 [feat] 내가 등록한 코스 -> 코스 상세 페이지 이동 기능 구현
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#233 [fix] 더보기를 통한 이동 시 스택이 쌓이는 문제 해결
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
Labels: 🐸 지현 🐸, 🫨 fix 🫨

#235 [feat] Navigation & BackStack
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnBoardingContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/navigation/SignInNavigation.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#237 [chore] 포인트 사용 [유저 데이트 코스 열람] API description 변경
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, 💗 chore 💗

#243 [init] Amplitude 기초 세팅
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/dateroad/DateRoadApp.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/amplitude/AmplitudeUtils.kt
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, ⚡️ init ⚡️

#240 [fix] 리이슈 중복 호출 후 마지막 호출에 의한 통신만 재전송하는 문제 해결
  app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
Labels: 🐸 지현 🐸, 🫨 fix 🫨

#245 [chore] 텍스트 변경사항 적용
  app/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#239 [chore] 프로필 수정 API 변경사항 적용 및 일부 로직 변경
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestEditProfileDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CostMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/textfield/DateRoadTextFieldWithButton.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#248 [chore] 엠티뷰, 에러뷰 이미지 변경
  app/src/main/java/org/sopt/dateroad/presentation/type/EmptyViewType.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadErrorView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailUnopenedDetail.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_empty_default.xml
  app/src/main/res/drawable/ic_empty_look.png
  app/src/main/res/drawable/ic_empty_my_page_enroll.xml
  app/src/main/res/drawable/ic_empty_read.png
  app/src/main/res/drawable/ic_empty_timeline.png
  app/src/main/res/drawable/ic_error_server.xml
  app/src/main/res/drawable/img_course_detail_dummy.png
  app/src/main/res/drawable/img_course_detail_is_not_access.png
  app/src/main/res/drawable/img_empty_envelope.xml
  app/src/main/res/drawable/img_empty_look.xml
  app/src/main/res/drawable/img_empty_read.xml
  app/src/main/res/drawable/img_empty_running.xml
  app/src/main/res/drawable/img_enroll_profile_default.xml
  app/src/main/res/drawable/img_error_server.xml
  app/src/main/res/drawable/img_loading_server.xml
  app/src/main/res/drawable/img_splash_logo.xml
Labels: 🐸 지현 🐸, 💗 chore 💗

#252 [chore] 로딩 뷰 Lottie로 변경
  app/build.gradle.kts
  app/src/main/assets/loading.json
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, 💗 chore 💗

#254 [fix] 닉네임이 전부 지워지지 않는 문제 해결
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, 🫨 fix 🫨

#257 [feat] 데이트 일정 뷰 앰플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#265 [feat] 코스 등록 + 일정 등록 (Enroll) 뷰 앰플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/navigation/CourseDetailNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/navigation/EnrollNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/look/navigation/LookNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/read/navigation/ReadNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#262 [feat] 내가 열람한 코스 뷰 앰플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐸 지현 🐸, ✨ feat ✨

#271 [fix] 2차 QA사항 반영
  app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
Labels: 🐸 지현 🐸, 🐻‍❄️ 민석 🐻‍❄️, 🫨 fix 🫨

#273 [feat] 릴리즈 준비
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/proguard-rules.pro
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, ✨ feat ✨

#276 [feat] User Property 트래킹 코드 심기
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/CourseRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/TimelineRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/UserPointRemoteDataSource.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/CourseRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/TimelineRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/UserPointRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseEnrollCourseDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseEnrollTimelineDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/model/response/ResponseUserUsePointDto.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/CourseService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/TimelineService.kt
  app/src/main/java/org/sopt/dateroad/data/dataremote/service/UserPointService.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseEnrollCourseDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseEnrollTimelineDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseUserUsePointDtoMapper.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/TimelineRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/data/repositoryimpl/UserPointRepositoryImpl.kt
  app/src/main/java/org/sopt/dateroad/domain/model/EnrollCourseResult.kt
  app/src/main/java/org/sopt/dateroad/domain/model/EnrollTimelineResult.kt
  app/src/main/java/org/sopt/dateroad/domain/model/PointUseResult.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/CourseRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/TimelineRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/repository/UserPointRepository.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostCourseUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostTimelineUseCase.kt
  app/src/main/java/org/sopt/dateroad/domain/usecase/PostUsePointUseCase.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#260 [feat] 홈 뷰 앰플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨

#264 [feat] 코스 상세 뷰 앰플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ feat ✨
